In [1]:
import pandas as pd

# data = [
#     [8.3252, 41, 6.984, 1.023, 322, 2.555, 37.88, -122.23, 4.526],
#     [8.3014, 21, 6.238, 0.971, 2401, 2.109, 37.86, -122.22, 3.585],
#     [7.2574, 52, 8.288, 1.073, 496, 2.802, 37.85, -122.24, 3.521],
#     [5.6431, 52, 5.817, 1.073, 558, 2.548, 37.85, -122.25, 3.413],
#     [3.8462, 52, 6.281, 1.081, 565, 2.181, 37.85, -122.25, 3.422],
#     [4.0368, 52, 4.761, 1.103, 413, 2.140, 37.85, -122.25, 2.697],
#     [3.6591, 52, 4.931, 0.951, 1094, 2.584, 37.84, -122.25, 2.992],
#     [3.1200, 42, 4.797, 1.061, 1157, 2.482, 37.84, -122.26, 2.414],
#     [2.0804, 50, 4.294, 1.118, 1206, 2.403, 37.84, -122.26, 1.907],
#     [3.6912, 52, 4.970, 1.047, 1551, 2.609, 37.84, -122.26, 2.413],
# ]

# columns = [
#     "MedInc",
#     "HouseAge",
#     "AveRooms",
#     "AveBedrms",
#     "Population",
#     "AveOccup",
#     "Latitude",
#     "Longitude",
#     "MedHouseVal",
# ]

# df = pd.DataFrame(data, columns=columns)
# df

In [2]:
df = pd.DataFrame({
    "English": [67, 87, 90],
    "Maths": [87, 57, 70],
    "Computer": [77, 71, 40],
}, index=["Hassan", "Musa", "Esha"])

In [6]:
df

        English  Maths  Computer  Stats
Hassan       67     87        77     90
Musa         87     57        71     78
Esha         90     70        40     78

In [121]:
def add_grace_marks(x):
    if x < 60:
        return x + 5
    else:
        return x

In [122]:
df.Maths = df.Maths.apply(add_grace_marks)

In [4]:
df["Stats"] = df.apply(lambda row: 90 if row["Maths"] > 85 else 78, axis=1)

In [5]:
df

        English  Maths  Computer  Stats
Hassan       67     87        77     90
Musa         87     57        71     78
Esha         90     70        40     78

In [137]:
df.loc["sum", :] = [1,1,1,1]

In [153]:
df = df.drop("total", axis=0)

In [144]:
df.loc["total", :] = [df["English"].sum(), df["Maths"].sum(), df["Maths"].sum(), df["Stats"].sum()]

In [155]:
df["Job"] = ["Programmer", "Programmer", "Designer"]

In [156]:
df

        English  Maths  Computer  Stats         Job
Hassan     67.0   87.0      77.0   90.0  Programmer
Musa       87.0   62.0      71.0   78.0  Programmer
Esha       90.0   70.0      40.0   78.0    Designer

In [158]:
df.groupby("Job").agg({
    "Maths": ["mean", "min", "max", "count"]
})

           Maths
            mean   min   max count
Job
Designer    70.0  70.0  70.0     1
Programmer  74.5  62.0  87.0     2

In [161]:
df.sort_values("English", ascending=False)

        English  Maths  Computer  Stats         Job
Esha       90.0   70.0      40.0   78.0    Designer
Musa       87.0   62.0      71.0   78.0  Programmer
Hassan     67.0   87.0      77.0   90.0  Programmer

In [162]:
df

        English  Maths  Computer  Stats         Job
Hassan     67.0   87.0      77.0   90.0  Programmer
Musa       87.0   62.0      71.0   78.0  Programmer
Esha       90.0   70.0      40.0   78.0    Designer

In [169]:
df[(df.Maths >= 70) & (df.Job.notna())]

        English  Maths  Computer  Stats         Job
Hassan     67.0   87.0      77.0   90.0  Programmer
Esha       90.0   70.0      40.0   78.0    Designer